server:
  port: 8087

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/inventory/**
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
        - id: delivery-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/deliveries/**
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
