version: '3.8'

services:
  product-db:
    image: postgres:15
    container_name: product_postgres
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

volumes:
  product_data:
