server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create  # можно заменить на validate, если позже добавим миграции
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: org.example.event.OrderCreatedEvent
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    org.example: DEBUG

app:
  kafka:
    bootstrap-servers: localhost:9092