version: '3.8'

services:
  inventory-db:
    image: postgres:15
    container_name: inventory_postgres
    environment:
      POSTGRES_DB: inventory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data

volumes:
  inventory_data:
